spring.application.name=CaoDangPhuongNam

# 1. K?t n?i (Dùng c?ng 6543 ?? tránh b? Timeout)
spring.datasource.url=jdbc:postgresql://db.jtyyfdpkevnjmdbcfjio.supabase.co:6543/postgres?prepareThreshold=0
spring.datasource.username=postgres
spring.datasource.password=0898988818Son123
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. C?u hình JPA/Hibernate quan tr?ng
# Ép tr?c ti?p Dialect ?? Hibernate không ph?i t? tìm ki?m (S?a l?i b?n ?ang g?p)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# 3. Naming Strategy
# Giúp mapping maMon -> ma_mon t? ??ng
#spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# B? dòng hibernate.temp.use_jdbc_metadata_defaults c? ?i vì nó gây l?i!