spring.application.name=CaoDangPhuongNam
# URL k?t n?i (?ã ghép ?úng host db.jtyyfdpkevnjmdbcfjio.supabase.co và port 5432)
spring.datasource.url=jdbc:postgresql://db.jtyyfdpkevnjmdbcfjio.supabase.co:5432/postgres

# User m?c ??nh
spring.datasource.username=postgres

# M?t kh?u
spring.datasource.password=0898988818Son123

# Driver c?a PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# Option ph? cho Hibernate ?? log SQL ra xem cho s??ng m?t
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true